# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Dependabot configuration for the client folder (Next.js)
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
  # Dependabot configuration for the api folder (Python - requirements.txt)
  - package-ecosystem: "pip"
    directory: "/api"
    schedule:
      interval: "weekly"
