version: "3.9"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"

  api:
    build:
      context: ./api
    ports:
      - "8080:8080"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - api
