version: "3.9"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"

  api:
    build:
      context: ./api
    ports:
      - "8080:8080"

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - client
      - api
    # Optional: Add volumes if additional files to mount
    # volumes:
    #   - ./ssl.crt:/etc/nginx/ssl.crt
    #   - ./ssl.key:/etc/nginx/ssl.key
    #   - ./custom-nginx.conf:/etc/nginx/nginx.conf
