"use client"
import { useState } from 'react'
import Nav from './components/Nav'
import './globals.css'
import type { Metadata } from 'next'
import { AuthModal } from './components/AuthModal'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {

  const [showModal, setShowModal] = useState(false);

  const openModal = () => setShowModal(true);
  const closeModal = () => setShowModal(false);
  
  return (
    <html lang="en">
      <body className='h-screen bg-white dark:bg-slate-900'>
          <Nav openModal={openModal}/>
          {children}
          <AuthModal show={showModal} onClose={closeModal}/>
        </body>
    </html>
  )
}
